config/routes.rb
Todo::Application.routes.draw do
  devise_for :users

  resources :tasks
  root :to => "tasks#index"

  resources :tasks do
    member do
      get 'do'
      get 'undo'
      get 'index_low'
      get 'index_medium'
      get 'index_high'
      get 'index_done'
      put 'do'
      put 'undo'
    end
  end

end

app/models/task.rb
class Task < ActiveRecord::Base
  def self.get_high_tasks
    Task.find_all_by_priority_and_complete(1, false);
  end
  def self.get_medium_tasks
    Task.find_all_by_priority_and_complete(2, false);
  end
  def self.get_low_tasks
    Task.find_all_by_priority_and_complete(3, false);
  end
  def self.get_done_tasks
    Task.find_all_by_complete(true);
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @tasks }
      format.js
    end
  end

  def index_high
    @tasks = Task.find_by_priority_and_complete(1, false);

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @tasks }
    end
  end

  def index_medium
    @tasks = Task.find_by_priority_and_complete(2, false)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @tasks }
    end
  end

  def index_low
    @tasks = Task.find_by_priority_and_complete(3, false)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @tasks }
    end
  end

  def index_done
    @tasks = Task.find_by_complete(true)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @tasks }
    end
  end


  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = Task.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @task }
    end
  end

  # PUT /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # PUT /tasks/1/do
  def do
    @task = Task.find(params[:id])
    @task.complete=true;
    @task.save;
    respond_to do |format|
      format.js
      format.html
    end
  end

  # PUT /tasks/1/undo
  def undo
    @task = Task.find(params[:id])
    @task.complete=false;
    @task.save;
    respond_to do |format|
      format.js
      format.html
    end
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(params[:task])
    if @task.save
      redirect_to tasks_path, :notice => 'Task was successfully created.'
    else
      format.html { render :action => "new" }
      format.json { render :json => @task.errors, :status => :unprocessable_entity }
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to @task, :notice => 'Task was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @task.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_menu.html.erb
<div id="menu">
  <a href="/tasks" class="menu_item item">My Tasks</a>
  <a href="/apps" class="menu_item item">APPS</a>
  <a href="/contact_us" class="menu_item last item">Contact Us</a>
</div>

app/views/layouts/_user_sign_in.html.erb
<%= form_for("user", :url => user_session_path) do |f| %>
<table>
  <tr>
    <td>
      <%= f.text_field :email %>
    </td>
    <td>
      <%= f.password_field :password %>
    </td>
    <td>
      <%= f.submit 'Sign in', :class => "small blue button" %>
    </td>
    <td>
      <!--<span class="item"></span>-->
        <span class="small orange button">
          <%= link_to "Sign up", new_user_registration_path %>
        </span>
    </td>
  </tr>
  <tr>
    <td>
      <%= f.check_box :remember_me %>
      <%= f.label :remember_me %>
    </td>
    <td>
      <%= link_to "Forgot your password?", new_password_path('user') %>
    </td>
  </tr>
</table>
<% end %>

app/views/layouts/_user_signed_in.html.erb
<table>
  <tr>
    <td>
      <%= current_user.email %>
    </td>
    <td>
       <span class="item"></span>
    </td>
    <td>
        <span class="small black button"><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></span>
    </td>
  </tr>

</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="page-container">
  <div id="header">
      <div id="site_logo">
          <%= image_tag("todo-icon-4.gif", :size=>"200x60")%>
      </div>
      <div id="user_signed_in">
        <% if user_signed_in? %>
           <%= render :partial => "layouts/user_signed_in" %>
        <% else %>
            <div id="user_sign_in_form">
                 <%= render :partial => "layouts/user_sign_in" %>
            </div>
        <% end %>
      </div>

      <%= render :partial => "layouts/menu" %>

  </div>

  <div id="content">
    <p class="notice"><%= notice %></p>

    <p class="alert"><%= alert %></p>

    <%= yield %>
  </div>
  <div id="footer">@copyright Sans</div>
</div>
</body>
</html>

app/views/tasks/_display_tasks.html.erb
<table id="tasks_table" >
  <tr>
    <td id="left_tasks_column">
      <div id="high_tasks" class="tasks round">
        <ul>
          <% if Task.get_high_tasks != nil %>
              <% Task.get_high_tasks.each do |task| %>
                  <li>
                        <%= form_for task, :url => url_for(:controller => 'tasks', :action => 'do', :id => task.id), :remote => true, :html => {:class => "task_form"} do |f| %>
                          <%= f.check_box 'complete', :class => "submittable" %>
                          <a href="<%= edit_task_path(task) %>">
                              <strong>
                                <%= task.description %>
                                <%= task.due_date %>
                              </strong>
                            </a>
                        <% end %>
                  </li>

              <% end %>
          <% end %>
        </ul>

      </div>
      <div id="medium_tasks" class="tasks round">

        <ul>
          <% if Task.get_medium_tasks != nil %>
          <% Task.get_medium_tasks.each do |task| %>
              <li>
                <%= form_for task, :url => url_for(:controller => 'tasks', :action => 'do', :id => task.id), :remote => true, :html => {:class => "task_form"} do |f| %>
                          <%= f.check_box 'complete', :class => "submittable" %>
                          <a href="<%= edit_task_path(task) %>">
                              <strong>
                                <%= task.description %>
                                <%= task.due_date %>
                              </strong>
                            </a>
                        <% end %>

              </li>

          <% end %>
              <% end %>
        </ul>

      </div>
    </td>
    <td id="right_tasks_column">
      <div id="low_tasks" class="tasks round">

        <ul>
          <% if Task.get_low_tasks != nil %>
          <% Task.get_low_tasks.each do |task| %>
              <li>
                <%= form_for task, :url => url_for(:controller => 'tasks', :action => 'do', :id => task.id), :remote => true, :html => {:class => "task_form"} do |f| %>
                          <%= f.check_box 'complete', :class => "submittable" %>
                          <a href="<%= edit_task_path(task) %>">
                              <strong>
                                <%= task.description %>
                                <%= task.due_date %>
                              </strong>
                            </a>
                        <% end %>
              </li>

          <% end %>
              <% end %>
        </ul>

      </div>

      <div id="done_tasks" class="tasks round">

        <ul>
          <% if Task.get_done_tasks != nil %>
          <% Task.get_done_tasks.each do |task| %>
              <li>
                <%= form_for task, :url => url_for(:controller => 'tasks', :action => 'undo', :id => task.id), :remote => true, :html => {:class => "task_form"} do |f| %>
                          <%= f.check_box 'complete', :class => "submittable" %>
                          <a href="<%= edit_task_path(task) %>">
                              <strong>
                                <%= task.description %>
                                <%= task.due_date %>
                              </strong>
                            </a>
                        <% end %>
              </li>

          <% end %>
              <% end %>
        </ul>

      </div>

    </td>
  </tr>
</table>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div>



<table id="new_form_container">
  <tr>
    <td colspan="2"><h1>Create a New task</h1></td>
  </tr>
  <tr>
    <td style="width:150px;"><%= f.label :description %></td>
    <td><%= f.text_field :description %></td>
  </tr>
  <tr>
    <td><%= f.label :priority %></td>
    <td><%= select("task", "priority", [['High', 1], ['Medium', 2], ['Low',3]]) %></td>
  </tr>
  <tr>
    <td>Due Date</td>
    <td><%= date_select :task, :due_date %></td>
  </tr>
  <tr>
    <td><%= submit_tag "Create New Task", :class => "small orange button"%></td>
    <td><%= link_to 'Back', tasks_path %></td>
  </tr>
</table>
</div>
<% end %>

app/views/tasks/do.js.erb
/*Replace the html of the div post_lists with the updated new one*/
$("#index_tasks_list").html("<%= escape_javascript( render(:partial => "tasks/display_tasks") ) %>");
$('.task_form').ajaxForm(function() {
    });

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<div id="app_buttons"><a href="<%=new_task_path%>" class="big_button round">Create New Task</a></div>
<div id="index_tasks_list">
  <%= render :partial => "tasks/display_tasks" %>
</div>


<!--<table>-->
<!--<tr>-->
<!--<th>Description</th>-->
<!--<th>Priority</th>-->
<!--<th>Seconds</th>-->
<!--<th>Complete</th>-->
<!--<th>Due Date</th>-->
<!--<th></th>-->
<!--<th></th>-->
<!--</tr>-->

<!--<% @tasks.each do |task| %>-->
    <!--<tr>-->
    <!--<td><%= task.description %></td>-->
    <!--<td><%= task.priority %></td>-->
    <!--<td><%= task.seconds %></td>-->
    <!--<td><%= task.complete %></td>-->
    <!--<td><%= task.due_date %></td>-->
    <!--<td><%= link_to 'Edit', edit_task_path(task) %></td>-->
    <!--<td><%= link_to 'Destroy', task, :confirm => 'Are you sure?', :method => :delete %></td>-->
    <!--</tr>-->
    <!--<% end %>-->
<!--</table>-->

app/views/tasks/index.js.erb
/*Replace the html of the div post_lists with the updated new one*/
alert("hi");
$("#index_tasks_list").html("<%= escape_javascript( render(:partial => "tasks/display_tasks") ) %>");

app/views/tasks/new.html.erb
<%= render 'form' %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @task.description %>
</p>

<p>
  <b>Priority:</b>
  <%= @task.priority %>
</p>

<p>
  <b>Seconds:</b>
  <%= @task.seconds %>
</p>


<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/undo.js.erb
/*Replace the html of the div post_lists with the updated new one*/
$("#index_tasks_list").html("<%= escape_javascript( render(:partial => "tasks/display_tasks") ) %>");
$('.task_form').ajaxForm(function() {
    });

app/views/tasks/update.js.erb
/*Replace the html of the div post_lists with the updated new one*/
alert("hi");
$("#index_tasks_list").html("<%= escape_javascript( render(:partial => "tasks/display_tasks") ) %>");